In [2]:
import numpy as np

In [7]:
a=np.array([9,0,2,1,0])

print(a)

a.shape

b=np.array([[5,3,1,9],[9,2,3,0]],dtype=np.float64)

print(b)


[9 0 2 1 0]
[[5. 3. 1. 9.]
 [9. 2. 3. 0.]]


In [ ]:
np.save('mfile.npy', b) #save array b to mfile.npy
np.load('mfile.npy')

In [17]:
c=np.zeros((9,9)) # size of array you want. Pad the values first

e=np.full((3,3),np.pi)

np.arange(10)

np.logspace(0,3,4) ## 10^0 to 10^3 by 4 spaces

array([   1.,   10.,  100., 1000.])

In [33]:
x=np.linspace(-1,1,3)
y=np.linspace(-1,1,3)
xx,yy=np.meshgrid(x,y)

idx=xx<0
idx

yy[idx]

array([-1.,  0.,  1.])

In [ ]:
plt.contourf(x,y,f,cmap='jet')